version: "3"

services:
  webserver:
    build:
      context: ./docker/php
    container_name: "${PROJECT_NAME}-php"
    ports:
      - "35:80"
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/:rw
      - ${PHP_INI-./docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MYSQL_PORT}
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=${XDEBUG_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - work-time-check

networks:
  work-time-check:
    driver: bridge